"use client";

import { ArrowLeft, Clock3, ExternalLink, Factory, Mail, MapPin, Radio, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { apiFetch, formatDate, humanize } from "@/lib/api";
import type { Incident, OverviewData, TerminalMapPoint } from "@/types";
import LeafletMap from "./LeafletMap";

export default function IncidentDetail({ id }: { id: string }) {
  const [item,setItem]=useState<Incident|null>(null); const [error,setError]=useState("");
  useEffect(()=>{apiFetch<Incident>(`/incidents/${id}`).then(setItem).catch(x=>setError(x.message));},[id]);
  const maxHistory=useMemo(()=>Math.max(1,...(item?.risk_history?.map(x=>Math.max(x.supply_risk,x.hsse_risk))||[1])),[item]);
  const mapData=useMemo<{incidents:OverviewData["map"];terminals:TerminalMapPoint[]}>(()=>{
    if(!item||item.status==="FALSE_POSITIVE"||item.latitude==null||item.longitude==null)return {incidents:[],terminals:[]};
    const terminals:TerminalMapPoint[]=[];
    if(item.nearest_terminal_id&&item.nearest_terminal&&item.nearest_terminal_latitude!=null&&item.nearest_terminal_longitude!=null)terminals.push({id:item.nearest_terminal_id,code:item.nearest_terminal_code||"TBBM",name:item.nearest_terminal,type:"NEAREST_TERMINAL",province:"",lat:item.nearest_terminal_latitude,lng:item.nearest_terminal_longitude});
    if(item.serving_terminal_id&&item.serving_terminal&&item.serving_terminal_latitude!=null&&item.serving_terminal_longitude!=null&&!terminals.some(x=>x.id===item.serving_terminal_id))terminals.push({id:item.serving_terminal_id,code:item.serving_terminal_code||"TBBM",name:item.serving_terminal,type:"SERVING_TERMINAL",province:"",lat:item.serving_terminal_latitude,lng:item.serving_terminal_longitude});
    return {incidents:[{id:item.id,code:item.incident_code,location:item.location,lat:item.latitude,lng:item.longitude,category:item.category,event:item.event,products:item.products,incident_date:item.date.slice(0,10),risk:item.risk,severity:item.severity,news:item.news_count,tiktok:item.tiktok_count,nearest_terminal:item.nearest_terminal,nearest_terminal_id:item.nearest_terminal_id,nearest_terminal_lat:item.nearest_terminal_latitude,nearest_terminal_lng:item.nearest_terminal_longitude,nearest_terminal_distance_km:item.nearest_terminal_distance_km,nearest_terminal_distance_source:item.nearest_terminal_distance_source,nearest_terminal_duration_minutes:item.nearest_terminal_duration_minutes,serving_terminal:item.serving_terminal,geocoding_provider:item.geocoding_provider,geocoding_confidence:item.geocoding_confidence}],terminals};
  },[item]);
  if(error) return <div className="p-10 text-red-600">{error}</div>;
  if(!item) return <div className="space-y-4 p-10"><div className="skeleton h-10 w-80"/><div className="skeleton h-64"/></div>;
  return <div className="px-5 pb-10 pt-5 md:px-8 lg:px-10 lg:pt-6"><Link href="/incidents" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-petrol"><ArrowLeft size={14}/> Incident register</Link>
    <header className="panel overflow-hidden"><div className="grid gap-5 bg-gradient-to-r from-[#0b73bf] to-[#075f9f] p-6 text-white md:grid-cols-[1fr_auto] md:p-8"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-lime-100">{item.incident_code} · {item.status==="FALSE_POSITIVE"?"FALSE POSITIVE":humanize(item.category)}</div><h1 className="mt-3 max-w-3xl font-serif text-3xl md:text-4xl">{item.status==="FALSE_POSITIVE"?`False positive · ${humanize(item.event)} detection`:`${humanize(item.event)} in ${item.location}`}</h1><div className="mt-4 flex flex-wrap gap-4 text-xs text-white/70"><span className="flex items-center gap-1.5"><Clock3 size={13}/>{formatDate(item.date,true)}</span><span className="flex items-center gap-1.5"><MapPin size={13}/>{item.location_resolution_status}</span><span className="flex items-center gap-1.5"><Radio size={13}/>{item.signal_count} signals</span></div></div><div className="self-center text-left md:text-right"><div className={`risk-badge risk-${item.severity}`}>{item.status==="FALSE_POSITIVE"?"FALSE POSITIVE":item.severity}</div><div className="mt-2 text-5xl font-bold tracking-tight">{Math.round(item.risk)}</div><div className="text-[10px] uppercase tracking-widest text-white/55">{item.status==="FALSE_POSITIVE"?"Excluded from intelligence":`${item.category==="HSSE"?"HSSE":"Supply"} risk score`}</div></div></div>
      <div className="grid grid-cols-2 divide-x divide-y divide-slate-200 md:grid-cols-4 md:divide-y-0">{[["News",item.news_count],["TikTok",item.tiktok_count],["Confidence",`${Math.round(item.confidence*100)}%`],["Trend",humanize(item.trend)]].map(([label,value])=><div key={label} className="p-4 md:p-5"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</div><div className="mt-2 font-serif text-xl">{value}</div></div>)}</div>
    </header>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><div className="space-y-5">
      {mapData.incidents.length>0&&<section className="panel p-5"><div className="eyebrow">OpenStreetMap · Leaflet</div><h2 className="mb-4 mt-1 font-serif text-xl">Lokasi kejadian dan TBBM</h2><LeafletMap incidents={mapData.incidents} terminals={mapData.terminals} heightClass="h-80" /></section>}
      <section className="panel p-5"><div className="eyebrow">Incident summary</div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><div className="text-[10px] font-bold uppercase text-slate-400">Products</div><div className="mt-2 flex flex-wrap gap-2">{item.products.map(x=><span key={x} className="rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-bold text-petrol">{x}</span>)}</div></div><div><div className="text-[10px] font-bold uppercase text-slate-400">Observed event types</div><div className="mt-2 text-sm font-bold">{item.event_types?.map(humanize).join(" · ")}</div></div><div><div className="text-[10px] font-bold uppercase text-slate-400">First detection</div><div className="mt-2 text-sm font-bold">{item.first_detection_source || "—"}</div>{item.tiktok_lead_time_minutes!=null&&<div className="mt-1 text-[10px] text-slate-400">TikTok lead: {item.tiktok_lead_time_minutes} min</div>}</div></div></section>
      <section className="panel p-5"><div className="flex items-center justify-between"><div><div className="eyebrow">Signal evidence</div><h2 className="mt-1 font-serif text-xl">Source corroboration</h2></div><span className="text-[10px] text-slate-400">TikTok = early signal · News = corroboration</span></div><div className="mt-5 space-y-3">{item.signals?.map(signal=>{const falsePositive=signal.processing_status==="ARCHIVED_FALSE_POSITIVE";const falsePositiveMessage=signal.false_positive_reason==="HOMEPAGE_NOT_ARTICLE"?"Homepage berisi kumpulan berita dan bukan satu artikel evidence.":"Tidak ada konteks berdekatan antara produk BBM dan indikasi gangguan.";return <article key={signal.id} className={`rounded-xl border p-4 ${falsePositive?"border-amber-300 bg-amber-50":"border-slate-200"}`}><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-black ${signal.source_type==="NEWS"?"bg-blue-50 text-blue-700":"bg-pink-50 text-pink-700"}`}>{signal.source_type}</span>{falsePositive?<span className="rounded-full bg-amber-200 px-2 py-1 text-[9px] font-black text-amber-900">FALSE POSITIVE</span>:signal.is_primary&&<span className="text-[9px] font-bold text-slate-400">PRIMARY SIGNAL</span>}<span className="ml-auto text-[10px] text-slate-400">{formatDate(signal.published_at,true)}</span></div><h3 className="mt-3 text-sm font-bold">{signal.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{signal.content}</p>{falsePositive&&<p className="mt-2 text-[10px] font-bold text-amber-800">{falsePositiveMessage}</p>}<div className="mt-3 flex items-center justify-between"><span className="text-[10px] text-slate-400">Confidence {falsePositive?0:signal.confidence ? Math.round(signal.confidence*100) : 0}%</span><a href={signal.url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-[10px] font-bold text-petrol">Original public signal <ExternalLink size={11}/></a></div></article>})}</div></section>
    </div><aside className="space-y-5">
      <section className="panel p-5"><div className="flex items-center gap-2"><Factory size={17} className="text-petrol"/><h2 className="font-serif text-xl">TBBM matching</h2></div><div className="mt-5 space-y-4"><div><div className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Nearest terminal</div><div className="mt-1 text-sm font-bold">{item.nearest_terminal||"Not resolved"}</div>{item.nearest_terminal_distance_km!=null&&<div className="text-[10px] text-slate-400">{item.nearest_terminal_distance_km} km · Durasi: Tidak dihitung · {humanize(item.nearest_terminal_distance_source||"unknown source")}</div>}</div><div className="border-t border-slate-200 pt-4"><div className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Serving terminal</div><div className="mt-1 text-sm font-bold">{item.serving_terminal||"No master mapping"}</div><div className="text-[10px] text-slate-400">Operational mapping, never inferred from distance</div></div></div></section>
      <section className="panel p-5"><div className="flex items-center gap-2"><ShieldAlert size={17} className="text-coral"/><h2 className="font-serif text-xl">Risk history</h2></div><div className="mt-5 flex h-36 items-end gap-1.5">{item.risk_history?.slice(-18).map((point,index)=>{const risk=Math.max(point.supply_risk,point.hsse_risk);return <div key={index} className="group relative flex-1 rounded-t-sm bg-petrol" style={{height:`${Math.max(4,risk/maxHistory*100)}%`}} title={`${risk} · ${formatDate(point.calculated_at,true)}`}/>})}</div><div className="mt-2 flex justify-between text-[9px] text-slate-400"><span>First calculation</span><span>Latest</span></div></section>
      <section className="panel p-5"><div className="flex items-center gap-2"><Mail size={17} className="text-petrol"/><h2 className="font-serif text-xl">Notifications</h2></div><div className="mt-4 space-y-3">{item.notifications?.length?item.notifications.map(notification=><div key={notification.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center justify-between"><strong className="text-xs">{notification.channel}</strong><span className={`risk-badge ${notification.status==="SENT"?"risk-NORMAL":notification.status==="FAILED"?"risk-CRITICAL":"risk-WATCH"}`}>{notification.status}</span></div><div className="mt-2 text-[10px] leading-5 text-slate-500">Provider: {notification.provider||"—"}<br/>Sender: {notification.sender||"—"}<br/>{notification.sent_at?`Sent: ${formatDate(notification.sent_at,true)}`:`Attempt: ${notification.attempts}/${notification.max_attempts}`}</div>{notification.reconnect_required&&<Link href="/settings?tab=notifications-email" className="mt-2 inline-block text-[10px] font-bold text-amber-700">Reconnect account</Link>}</div>):<div className="text-xs text-slate-400">No email notification job for this incident.</div>}</div></section>
      <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><strong>Media intelligence boundary.</strong> This record represents reported signals and does not claim a complete actual incident population.</section>
    </aside></div>
  </div>;
}
