"use client";

import {
  Activity, AlertTriangle, CheckCircle2, Coins, ExternalLink, KeyRound,
  Loader2, Play, Plus, RefreshCw, Save, Search, Smartphone, Trash2, XCircle,
} from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { apiFetch, formatDate, humanize } from "@/lib/api";
import PageHeader from "./PageHeader";
import SignalPage from "./SignalPage";

export type TikTokDiscoverySection = "overview" | "public-signals" | "keywords" | "manual-search" | "videos" | "runs" | "settings";

type Health = {status:string;lastCheckedAt?:string;lastSuccessfulRequestAt?:string;lastError?:string;requestsToday:number;creditsToday:number;creditsThisMonth:number};
type DiscoverySettings = {
  provider:string;apiKeyConfigured:boolean;apiKeyMasked?:string;credentialSource?:string;credentialError?:string;enabled:boolean;
  defaultRegion:string;defaultDateFilter:string;defaultSortBy:string;defaultMaxPages:number;defaultTrim:boolean;
  transcriptEnabled:boolean;aiTranscriptFallbackEnabled:boolean;downloadMediaEnabled:boolean;
  globalDiscoveryIntervalMinutes:number;dailyCreditLimit?:number;monthlyCreditLimit?:number;
  warningThresholdPercent:number;criticalThresholdPercent:number;adaptiveSchedulerEnabled:boolean;health:Health;
};
type Keyword = {
  id:string;keyword:string;category?:string;priority:"HIGH"|"MEDIUM"|"LOW";frequencyMinutes?:number;
  effectiveFrequencyMinutes:number;usesGlobalInterval:boolean;active:boolean;dateFilter?:string;sortBy?:string;
  region?:string;maxPages?:number;lastRunAt?:string;nextRunAt?:string;lastResultCount:number;
  lastNewVideoCount:number;lastRelevantCount:number;
};
type SearchRun = {
  id:string;keyword:string;provider:string;startedAt:string;finishedAt?:string;durationSeconds?:number;status:string;
  pages:number;apiRequests:number;credits:number;results:number;newVideos:number;duplicates:number;relevant:number;
  irrelevant:number;uncertain:number;transcriptsRequested:number;transcriptsFound:number;incidents:number;error?:string;
  timeline?:{operation:string;at:string;succeeded:boolean;credits:number;durationMs?:number;error?:string}[];
};
type Video = {
  id:string;providerVideoId:string;url:string;thumbnailUrl?:string;author:string;authorDisplayName?:string;caption?:string;
  hashtags:string[];createdAt?:string;firstSeenAt:string;views:number;likes:number;comments:number;shares:number;
  matchedKeywords:string[];relevanceScore?:number;category?:string;location?:string;nearestTbbm?:string;
  processingStatus:string;incidentId?:number;incidentCode?:string;
};
type Dashboard = {
  period:string;kpis:{videosDiscovered:number;newVideos:number;relevantVideos:number;tiktokIncidents:number;creditsToday:number;creditsThisMonth:number};
  videosOverTime:{date:string;count:number}[];byCategory:{category:string;count:number}[];byKeyword:{keyword:string;count:number}[];
  topLocations:{location:string;count:number}[];recentVideos:Video[];
};
type Usage = {
  today:{search_credits:number;transcript_credits:number;video_info_credits:number;health_credits:number;total_credits:number;requests:number};
  month:{search_credits:number;transcript_credits:number;video_info_credits:number;health_credits:number;total_credits:number;requests:number};
  monthlyLimit?:number;remainingBudget?:number;projectedMonthEndUsage:number;creditsPerRelevantVideo?:number;creditsPerIncident?:number;
};

const inputClass = "h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-xs outline-none focus:border-petrol";
const buttonPrimary = "inline-flex items-center justify-center gap-2 rounded-lg bg-ink px-4 py-2.5 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-50";
const buttonSecondary = "inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 disabled:opacity-50";

async function adminFetch<T>(path:string, init:RequestInit = {}):Promise<T>{
  const response = await fetch(`/tiktok-discovery-api/${path}`, {
    ...init,
    headers:{Accept:"application/json","Content-Type":"application/json",...init.headers},
  });
  const payload = await response.json().catch(()=>null) as ({detail?:string}&T)|null;
  if(!response.ok) throw new Error(payload?.detail || `API request failed (${response.status})`);
  return payload as T;
}

function valueOrDash(value:string|number|undefined|null){return value === undefined || value === null || value === "" ? "—" : value;}
function formatMaybeDate(value?:string){return value ? formatDate(value,true) : "—";}
function intervalLabel(minutes:number){return minutes % 60 === 0 ? `${minutes/60} jam` : `${minutes} menit`;}

export default function TikTokDiscoveryConsole({section}:{section:TikTokDiscoverySection}){
  const titles:Record<TikTokDiscoverySection,[string,string]> = {
    overview:["TikTok Discovery Overview","Monitoring kandidat publik, relevansi, insiden, dan konsumsi credit."],
    "public-signals":["TikTok public signals","Bukti publik TikTok yang sudah masuk ke pipeline signal dan hubungan incident."],
    keywords:["TikTok Keywords","Atur cakupan pencarian dan jadwal efektif setiap keyword."],
    "manual-search":["Manual TikTok Search","Jalankan discovery ad-hoc melalui pipeline dan audit run yang sama."],
    videos:["TikTok Video Feed","Metadata publik, hasil screening, enrichment, dan hubungan insiden."],
    runs:["TikTok Search Runs","Audit setiap pencarian, request provider, credit, hasil, dan error."],
    settings:["TikTok Discovery Settings","Konfigurasi provider server-side, schedule, enrichment, dan credit protection."],
  };
  return <div className="px-5 pb-12 pt-5 md:px-8 lg:px-10 lg:pt-6">
    <PageHeader eyebrow="TikTok Discovery" title={titles[section][0]} description={titles[section][1]} />
    <DiscoveryTabs active={section}/>
    {section === "overview" && <Overview/>}
    {section === "public-signals" && <SignalPage type="tiktok" embedded/>}
    {section === "keywords" && <Keywords/>}
    {section === "manual-search" && <ManualSearch/>}
    {section === "videos" && <Videos/>}
    {section === "runs" && <Runs/>}
    {section === "settings" && <Settings/>}
  </div>;
}

function DiscoveryTabs({active}:{active:TikTokDiscoverySection}){
  const tabs:[TikTokDiscoverySection,string][] = [["overview","Overview"],["public-signals","TikTok public signals"],["keywords","Keywords"],["manual-search","Manual Search"],["videos","Videos"],["runs","Runs"],["settings","Settings"]];
  return <div className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-200 pb-3">
    {tabs.map(([id,label])=><Link key={id} href={id === "overview" ? "/tiktok-discovery" : `/tiktok-discovery/${id}`} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold ${active===id?"bg-ink text-white":"bg-white text-slate-500 hover:text-ink"}`}>{label}</Link>)}
  </div>;
}

function Overview(){
  const [period,setPeriod]=useState("24h");const [data,setData]=useState<Dashboard|null>(null);const [usage,setUsage]=useState<Usage|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(()=>{setLoading(true);setError("");Promise.all([apiFetch<Dashboard>(`/tiktok/dashboard?period=${period}`),apiFetch<Usage>("/tiktok/usage")]).then(([dashboard,nextUsage])=>{setData(dashboard);setUsage(nextUsage);}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false));},[period]);
  useEffect(()=>{load();},[load]);
  if(loading)return <Loading/>;if(error)return <ErrorBox message={error} retry={load}/>;if(!data)return null;
  const kpis=[
    ["Videos Discovered",data.kpis.videosDiscovered,Smartphone],["New Videos",data.kpis.newVideos,Plus],
    ["Relevant Videos",data.kpis.relevantVideos,CheckCircle2],["TikTok Incidents",data.kpis.tiktokIncidents,AlertTriangle],
    ["Credits Today",data.kpis.creditsToday,Coins],["Credits This Month",data.kpis.creditsThisMonth,Activity],
  ] as const;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-slate-500">TikTok adalah early signal; News tetap menjadi corroboration layer.</div><div className="flex gap-2">{[["24h","24 jam"],["7d","7 hari"],["30d","30 hari"]].map(([id,label])=><button key={id} onClick={()=>setPeriod(id)} className={`rounded-lg px-3 py-2 text-xs font-bold ${period===id?"bg-petrol text-white":"border border-slate-300 bg-white"}`}>{label}</button>)}<button onClick={load} className={buttonSecondary} aria-label="Refresh"><RefreshCw size={14}/></button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{kpis.map(([label,value,Icon])=><div className="panel p-5" key={label}><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</span><Icon size={17} className="text-petrol"/></div><div className="mt-3 font-serif text-3xl">{value.toLocaleString("id-ID")}</div></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><MiniChart title="Videos Discovered Over Time" items={data.videosOverTime.map(item=>({label:item.date,value:item.count}))}/><MiniChart title="Relevant TikTok by Incident Category" items={data.byCategory.map(item=>({label:humanize(item.category),value:item.count}))}/><MiniChart title="Videos by Keyword" items={data.byKeyword.map(item=>({label:item.keyword,value:item.count}))}/><MiniChart title="Top Locations" items={data.topLocations.map(item=>({label:item.location,value:item.count}))}/></div>
    {usage&&<UsageCard data={usage}/>}<VideoTable rows={data.recentVideos}/>
  </div>;
}

function MiniChart({title,items}:{title:string;items:{label:string;value:number}[]}){
  const max=Math.max(1,...items.map(item=>item.value));
  return <section className="panel p-5"><h2 className="font-serif text-lg">{title}</h2><div className="mt-5 space-y-3">{items.length===0?<Empty text="Belum ada data pada periode ini."/>:items.slice(0,10).map(item=><div key={item.label}><div className="mb-1 flex justify-between gap-4 text-[11px]"><span className="truncate font-bold">{item.label}</span><span>{item.value}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-petrol" style={{width:`${Math.max(4,item.value/max*100)}%`}}/></div></div>)}</div></section>;
}

function Keywords(){
  const [rows,setRows]=useState<Keyword[]>([]);const [editing,setEditing]=useState<Keyword|null>(null);const [adding,setAdding]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);
  const load=useCallback(()=>apiFetch<Keyword[]>("/tiktok/keywords").then(setRows).catch(reason=>setError(reason.message)).finally(()=>setLoading(false)),[]);useEffect(()=>{load();},[load]);
  const run=async(id:string)=>{try{const result=await adminFetch<{run_id:string}>(`keywords/${id}/run`,{method:"POST",body:"{}"});setNotice(`Run ${result.run_id} masuk queue.`);await load();}catch(reason){setError((reason as Error).message);}};
  const disable=async(row:Keyword)=>{try{await adminFetch(`keywords/${row.id}`,{method:"PUT",body:JSON.stringify({active:!row.active})});await load();}catch(reason){setError((reason as Error).message);}};
  const remove=async(id:string)=>{try{await adminFetch(`keywords/${id}`,{method:"DELETE"});setNotice("Keyword dinonaktifkan dan histori tetap dipertahankan.");await load();}catch(reason){setError((reason as Error).message);}};
  if(loading)return <Loading/>;
  return <div className="space-y-5">{(error||notice)&&<Toast error={error} message={notice} close={()=>{setError("");setNotice("");}}/>}<div className="flex justify-end"><button className={buttonPrimary} onClick={()=>{setAdding(true);setEditing(null);}}><Plus size={14}/>Add Keyword</button></div>
    {(adding||editing)&&<KeywordForm value={editing} close={()=>{setAdding(false);setEditing(null);}} saved={async()=>{setAdding(false);setEditing(null);setNotice("Keyword tersimpan.");await load();}}/>}
    <div className="panel overflow-hidden"><div className="scroll-table"><table className="data-table"><thead><tr><th>Keyword</th><th>Category</th><th>Priority</th><th>Interval</th><th>Status</th><th>Last Run</th><th>Next Run</th><th>Results</th><th>New</th><th>Relevant</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="font-bold">{row.keyword}</td><td>{valueOrDash(row.category)}</td><td><StatusBadge value={row.priority}/></td><td>{intervalLabel(row.effectiveFrequencyMinutes)}{row.usesGlobalInterval&&<div className="text-[9px] text-slate-400">Global</div>}</td><td><StatusBadge value={row.active?"ACTIVE":"DISABLED"}/></td><td>{formatMaybeDate(row.lastRunAt)}</td><td>{formatMaybeDate(row.nextRunAt)}</td><td>{row.lastResultCount}</td><td>{row.lastNewVideoCount}</td><td>{row.lastRelevantCount}</td><td><div className="flex flex-wrap gap-1"><button className={buttonSecondary} onClick={()=>{setEditing(row);setAdding(false);}}>Edit</button><button className={buttonSecondary} onClick={()=>run(row.id)}><Play size={12}/>Run</button><button className={buttonSecondary} onClick={()=>disable(row)}>{row.active?"Disable":"Enable"}</button><button className="rounded-lg border border-red-200 p-2 text-red-600" onClick={()=>remove(row.id)} aria-label="Delete"><Trash2 size={13}/></button></div></td></tr>)}</tbody></table></div>{rows.length===0&&<Empty text="Belum ada keyword TikTok."/>}</div>
  </div>;
}

function KeywordForm({value,close,saved}:{value:Keyword|null;close:()=>void;saved:()=>void}){
  const [keyword,setKeyword]=useState(value?.keyword||"");const [category,setCategory]=useState(value?.category||"STOCKOUT");const [priority,setPriority]=useState(value?.priority||"MEDIUM");const [useGlobal,setUseGlobal]=useState(value?.usesGlobalInterval??true);const [frequency,setFrequency]=useState(String(value?.frequencyMinutes||60));const [region,setRegion]=useState(value?.region||"");const [dateFilter,setDateFilter]=useState(value?.dateFilter||"");const [sortBy,setSortBy]=useState(value?.sortBy||"");const [maxPages,setMaxPages]=useState(value?.maxPages?String(value.maxPages):"");const [active,setActive]=useState(value?.active??true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");const payload={keyword,category,priority,frequency_minutes:useGlobal?null:Number(frequency),use_global_interval:useGlobal,active,region:region||null,date_filter:dateFilter||null,sort_by:sortBy||null,max_pages:maxPages?Number(maxPages):null};try{await adminFetch(value?`keywords/${value.id}`:"keywords",{method:value?"PUT":"POST",body:JSON.stringify(payload)});saved();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
  return <form onSubmit={submit} className="panel p-5"><div className="flex items-center justify-between"><h2 className="font-serif text-xl">{value?"Edit Keyword":"Add Keyword"}</h2><button type="button" onClick={close}><XCircle size={18}/></button></div>{error&&<p className="mt-3 text-xs text-red-600">{error}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Keyword"><input className={inputClass} value={keyword} onChange={e=>setKeyword(e.target.value)} required/></Field><Field label="Category"><select className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}>{["STOCKOUT","SHORTAGE","QUEUE","RESTRICTION","TANKER_INCIDENT","SPBU_DISRUPTION"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select className={inputClass} value={priority} onChange={e=>setPriority(e.target.value as "HIGH"|"MEDIUM"|"LOW")}>{["HIGH","MEDIUM","LOW"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><Toggle checked={active} onChange={setActive} label={active?"Active":"Disabled"}/></Field><Field label="Use Global Interval"><Toggle checked={useGlobal} onChange={setUseGlobal} label={useGlobal?"Global":"Override"}/></Field>{!useGlobal&&<Field label="Interval (minutes)"><input type="number" min="5" className={inputClass} value={frequency} onChange={e=>setFrequency(e.target.value)}/></Field>}<Field label="Region Override"><input className={inputClass} value={region} onChange={e=>setRegion(e.target.value.toUpperCase())} placeholder="Use Default"/></Field><Field label="Date Override"><select className={inputClass} value={dateFilter} onChange={e=>setDateFilter(e.target.value)}><option value="">Use Default</option>{["yesterday","this-week","this-month","all-time"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Sort Override"><select className={inputClass} value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="">Use Default</option>{["date-posted","relevance","most-liked"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Max Pages Override"><input type="number" min="1" max="10" className={inputClass} value={maxPages} onChange={e=>setMaxPages(e.target.value)} placeholder="Use Default"/></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" className={buttonSecondary} onClick={close}>Cancel</button><button disabled={busy} className={buttonPrimary}>{busy?<Loader2 className="animate-spin" size={14}/>:<Save size={14}/>}Save Keyword</button></div></form>;
}

function ManualSearch(){
  const [query,setQuery]=useState("");const [region,setRegion]=useState("ID");const [datePosted,setDatePosted]=useState("this-week");const [sortBy,setSortBy]=useState("date-posted");const [maxPages,setMaxPages]=useState("2");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");setError("");try{const result=await adminFetch<{run_id:string}>("manual-search",{method:"POST",body:JSON.stringify({query,region,date_posted:datePosted,sort_by:sortBy,max_pages:Number(maxPages)})});setMessage(`Discovery dijadwalkan. Run ID: ${result.run_id}`);}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
  return <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><form onSubmit={submit} className="panel p-6"><h2 className="font-serif text-xl">Search TikTok</h2><p className="mt-2 text-xs leading-5 text-slate-500">Manual search tetap membuat audit run, dedup video, relevance screening, transcript selektif, dan incident matching.</p>{(message||error)&&<div className={`mt-4 rounded-lg p-3 text-xs ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-800"}`}>{error||message}</div>}<div className="mt-6 space-y-4"><Field label="Keyword"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={15}/><input className={`${inputClass} pl-9`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="solar langka di Riau" required/></div></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Region"><select className={inputClass} value={region} onChange={e=>setRegion(e.target.value)}><option value="ID">Indonesia (ID)</option></select></Field><Field label="Date"><select className={inputClass} value={datePosted} onChange={e=>setDatePosted(e.target.value)}>{["yesterday","this-week","this-month","all-time"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Sort"><select className={inputClass} value={sortBy} onChange={e=>setSortBy(e.target.value)}>{["date-posted","relevance","most-liked"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Max Pages"><input type="number" min="1" max="10" className={inputClass} value={maxPages} onChange={e=>setMaxPages(e.target.value)}/></Field></div></div><button disabled={busy} className={`${buttonPrimary} mt-6`}>{busy?<Loader2 className="animate-spin" size={14}/>:<Search size={14}/>}Search TikTok</button></form><section className="panel p-5"><h2 className="font-serif text-lg">Guardrails</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-slate-500"><li>• Hanya metadata konten publik.</li><li>• Region adalah proxy preference, bukan bukti lokasi.</li><li>• Pagination dibatasi sesuai Max Pages.</li><li>• Video lama tidak ditranskrip atau diklasifikasi ulang tanpa reprocess.</li><li>• Download media tetap nonaktif.</li></ul></section></div>;
}

function Videos(){const [rows,setRows]=useState<Video[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const load=useCallback(()=>{setLoading(true);apiFetch<{items:Video[]}>("/tiktok/videos?limit=200").then(data=>setRows(data.items)).catch(reason=>setError(reason.message)).finally(()=>setLoading(false));},[]);useEffect(()=>{load();},[load]);const reprocess=async(id:string)=>{try{await adminFetch(`videos/${id}/reprocess`,{method:"POST",body:JSON.stringify({force:true})});await load();}catch(reason){setError((reason as Error).message);}};if(loading)return <Loading/>;if(error)return <ErrorBox message={error} retry={load}/>;return <VideoTable rows={rows} onReprocess={reprocess}/>;}

function VideoTable({rows,onReprocess}:{rows:Video[];onReprocess?:(id:string)=>void}){return <section className="panel overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-serif text-xl">TikTok Video Feed</h2></div>{rows.length===0?<Empty text="Belum ada video discovery."></Empty>:<div className="scroll-table"><table className="data-table"><thead><tr><th>Video</th><th>Author / Created</th><th>Engagement</th><th>Keywords</th><th>Relevance</th><th>Location / TBBM</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><div className="flex min-w-72 gap-3">{row.thumbnailUrl?<img src={row.thumbnailUrl} alt="" referrerPolicy="no-referrer" className="h-16 w-11 rounded-md object-cover"/>:<div className="flex h-16 w-11 items-center justify-center rounded-md bg-slate-100"><Smartphone size={16}/></div>}<div><p className="line-clamp-3 text-xs font-bold">{row.caption||"Tanpa caption"}</p><div className="mt-1 text-[9px] text-slate-400">{row.hashtags.map(tag=>`#${tag}`).join(" ")}</div></div></div></td><td><div className="font-bold">{row.author}</div><div className="mt-1 text-[10px] text-slate-400">{formatMaybeDate(row.createdAt||row.firstSeenAt)}</div></td><td className="whitespace-nowrap text-xs">{row.views.toLocaleString("id-ID")} views<br/>{row.likes.toLocaleString("id-ID")} likes<br/>{row.comments.toLocaleString("id-ID")} comments</td><td><div className="flex max-w-52 flex-wrap gap-1">{row.matchedKeywords.map(keyword=><span key={keyword} className="rounded bg-slate-100 px-2 py-1 text-[9px]">{keyword}</span>)}</div></td><td><div className="font-bold">{row.relevanceScore===undefined?"—":`${Math.round(row.relevanceScore*100)}%`}</div><div className="mt-1 text-[9px] text-slate-400">{row.category?humanize(row.category):"Unclassified"}</div></td><td><div className="font-bold">{valueOrDash(row.location)}</div><div className="mt-1 text-[9px] text-slate-400">Nearest: {valueOrDash(row.nearestTbbm)}</div></td><td><StatusBadge value={row.processingStatus}/></td><td><div className="flex gap-2"><a href={row.url} target="_blank" rel="noreferrer" className={buttonSecondary}><ExternalLink size={12}/>Open</a>{row.incidentId&&<Link href={`/incidents/${row.incidentId}`} className={buttonSecondary}>Incident</Link>}{onReprocess&&<button className={buttonSecondary} onClick={()=>onReprocess(row.id)}><RefreshCw size={12}/></button>}</div></td></tr>)}</tbody></table></div>}</section>;}

function Runs(){
  const [rows,setRows]=useState<SearchRun[]>([]);const [detail,setDetail]=useState<SearchRun|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const load=useCallback(()=>apiFetch<{items:SearchRun[]}>("/tiktok/search-runs?limit=200").then(data=>setRows(data.items)).catch(reason=>setError(reason.message)).finally(()=>setLoading(false)),[]);useEffect(()=>{load();},[load]);const open=async(id:string)=>{try{setDetail(await apiFetch<SearchRun>(`/tiktok/search-runs/${id}`));}catch(reason){setError((reason as Error).message);}};if(loading)return <Loading/>;if(error)return <ErrorBox message={error} retry={load}/>;
  return <div className="space-y-5">{detail&&<section className="panel p-5"><div className="flex items-center justify-between"><div><div className="eyebrow">Run detail</div><h2 className="mt-1 font-serif text-xl">{detail.keyword}</h2></div><button onClick={()=>setDetail(null)}><XCircle size={18}/></button></div>{detail.error&&<div className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-700">{detail.error}</div>}<div className="mt-5 grid gap-3 md:grid-cols-3">{detail.timeline?.map((item,index)=><div key={`${item.at}-${index}`} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between"><span className="text-xs font-bold">{item.operation}</span><StatusBadge value={item.succeeded?"SUCCESS":"FAILED"}/></div><div className="mt-2 text-[10px] text-slate-400">{formatMaybeDate(item.at)} · {item.credits} credits · {item.durationMs||0} ms</div>{item.error&&<p className="mt-2 text-xs text-red-600">{item.error}</p>}</div>)}</div></section>}<section className="panel overflow-hidden"><div className="scroll-table"><table className="data-table"><thead><RunHeaders/></thead><tbody>{rows.map(row=><tr key={row.id} onClick={()=>open(row.id)} className="cursor-pointer"><td className="font-mono text-[10px]">{row.id.slice(0,8)}</td><td className="font-bold">{row.keyword}</td><td>{formatMaybeDate(row.startedAt)}</td><td>{row.durationSeconds?`${row.durationSeconds.toFixed(1)}s`:"—"}</td><td><StatusBadge value={row.status}/></td><td>{row.pages}</td><td>{row.apiRequests}</td><td>{row.credits}</td><td>{row.results}</td><td>{row.newVideos}</td><td>{row.duplicates}</td><td>{row.relevant}</td><td>{row.transcriptsFound}</td><td>{row.incidents}</td></tr>)}</tbody></table></div>{rows.length===0&&<Empty text="Belum ada search run."/>}</section></div>;
}
function RunHeaders(){return <tr><th>Run ID</th><th>Keyword</th><th>Started</th><th>Duration</th><th>Status</th><th>Pages</th><th>API</th><th>Credits</th><th>Results</th><th>New</th><th>Duplicates</th><th>Relevant</th><th>Transcripts</th><th>Incidents</th></tr>;}

function Settings(){
  const [current,setCurrent]=useState<DiscoverySettings|null>(null);const [draft,setDraft]=useState<Record<string,string|boolean>>({});const [apiKey,setApiKey]=useState("");const [showKey,setShowKey]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const load=useCallback(()=>apiFetch<DiscoverySettings>("/tiktok/settings").then(value=>{setCurrent(value);setDraft({enabled:value.enabled,defaultRegion:value.defaultRegion,defaultDateFilter:value.defaultDateFilter,defaultSortBy:value.defaultSortBy,defaultMaxPages:String(value.defaultMaxPages),defaultTrim:value.defaultTrim,transcriptEnabled:value.transcriptEnabled,aiTranscriptFallbackEnabled:value.aiTranscriptFallbackEnabled,downloadMediaEnabled:value.downloadMediaEnabled,globalDiscoveryIntervalMinutes:String(value.globalDiscoveryIntervalMinutes),dailyCreditLimit:value.dailyCreditLimit?String(value.dailyCreditLimit):"",monthlyCreditLimit:value.monthlyCreditLimit?String(value.monthlyCreditLimit):"",warningThresholdPercent:String(value.warningThresholdPercent),criticalThresholdPercent:String(value.criticalThresholdPercent),adaptiveSchedulerEnabled:value.adaptiveSchedulerEnabled});}).catch(reason=>setError(reason.message)),[]);useEffect(()=>{load();},[load]);
  const update=(key:string,value:string|boolean)=>setDraft(state=>({...state,[key]:value}));
  const test=async()=>{setBusy(true);setError("");setNotice("");try{const result=await adminFetch<{status:string;credits_remaining?:number}>("settings/test-connection",{method:"POST",body:JSON.stringify(apiKey?{api_key:apiKey}:{})});setNotice(`Connection ${result.status}. Remaining provider credits: ${valueOrDash(result.credits_remaining)}.`);await load();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
  const save=async()=>{setBusy(true);setError("");setNotice("");const numberOrNull=(key:string)=>draft[key]?Number(draft[key]):null;const payload={provider:"SCRAPECREATORS",...(apiKey?{api_key:apiKey}:{}),enabled:Boolean(draft.enabled),default_region:draft.defaultRegion,default_date_filter:draft.defaultDateFilter,default_sort_by:draft.defaultSortBy,default_max_pages:Number(draft.defaultMaxPages),default_trim:Boolean(draft.defaultTrim),transcript_enabled:Boolean(draft.transcriptEnabled),ai_transcript_fallback_enabled:Boolean(draft.aiTranscriptFallbackEnabled),download_media_enabled:Boolean(draft.downloadMediaEnabled),global_discovery_interval_minutes:Number(draft.globalDiscoveryIntervalMinutes),daily_credit_limit:numberOrNull("dailyCreditLimit"),monthly_credit_limit:numberOrNull("monthlyCreditLimit"),warning_threshold_percent:Number(draft.warningThresholdPercent),critical_threshold_percent:Number(draft.criticalThresholdPercent),adaptive_scheduler_enabled:Boolean(draft.adaptiveSchedulerEnabled)};try{await adminFetch("settings",{method:"PUT",body:JSON.stringify(payload)});setApiKey("");setNotice("TikTok Discovery settings tersimpan.");await load();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}};
  if(!current)return error?<ErrorBox message={error} retry={load}/>:<Loading/>;
  return <div className="space-y-5">{(error||notice)&&<Toast error={error} message={notice} close={()=>{setError("");setNotice("");}}/>}{current.credentialError&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-xs font-bold text-red-700">{current.credentialError}</div>}<section className="panel p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="eyebrow">Provider</div><h2 className="mt-1 font-serif text-xl">TikTok Provider</h2></div><StatusBadge value={current.health.status}/></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Provider"><select className={inputClass} disabled><option>ScrapeCreators</option></select></Field><Field label="Discovery"><Toggle checked={Boolean(draft.enabled)} onChange={value=>update("enabled",value)} label={draft.enabled?"Enabled":"Disabled"}/></Field><Field label="API Key"><div className="relative"><KeyRound className="absolute left-3 top-3 text-slate-400" size={15}/><input type={showKey?"text":"password"} className={`${inputClass} pl-9 pr-16`} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={current.apiKeyMasked||(current.credentialError?"Enter API key again":"Enter ScrapeCreators API key")}/><button type="button" className="absolute right-3 top-2.5 text-[10px] font-bold" onClick={()=>setShowKey(x=>!x)}>{showKey?"Hide":"Show"}</button></div><p className="mt-1 text-[10px] text-slate-400">Existing key tidak pernah dikirim kembali oleh backend.</p></Field><div className="flex items-end"><button disabled={busy} type="button" className={buttonSecondary} onClick={test}>{busy?<Loader2 className="animate-spin" size={14}/>:<Activity size={14}/>}Test Connection</button></div></div></section>
    <section className="panel p-6"><div className="eyebrow">Schedule</div><h2 className="mt-1 font-serif text-xl">Discovery Schedule</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Global Interval (minutes)"><input type="number" min="5" className={inputClass} value={String(draft.globalDiscoveryIntervalMinutes)} onChange={e=>update("globalDiscoveryIntervalMinutes",e.target.value)}/><div className="mt-2 flex flex-wrap gap-2">{[[30,"30 min"],[60,"1 hour"],[180,"3 hours"],[360,"6 hours"]].map(([value,label])=><button key={value} type="button" className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-bold" onClick={()=>update("globalDiscoveryIntervalMinutes",String(value))}>{label}</button>)}</div><p className="mt-2 text-[10px] text-slate-400">Digunakan keyword tanpa interval khusus.</p></Field><Field label="Adaptive Scheduling"><Toggle checked={Boolean(draft.adaptiveSchedulerEnabled)} onChange={value=>update("adaptiveSchedulerEnabled",value)} label={draft.adaptiveSchedulerEnabled?"On":"Off"}/><p className="mt-2 text-[10px] leading-4 text-slate-400">Meningkatkan frekuensi sementara saat terjadi lonjakan, tanpa mengubah interval user.</p></Field></div></section>
    <section className="panel p-6"><div className="eyebrow">Search</div><h2 className="mt-1 font-serif text-xl">Default Search Configuration</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label="Default Region"><select className={inputClass} value={String(draft.defaultRegion)} onChange={e=>update("defaultRegion",e.target.value)}><option value="ID">Indonesia (ID)</option></select></Field><Field label="Date Filter"><select className={inputClass} value={String(draft.defaultDateFilter)} onChange={e=>update("defaultDateFilter",e.target.value)}>{["yesterday","this-week","this-month","all-time"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Sort"><select className={inputClass} value={String(draft.defaultSortBy)} onChange={e=>update("defaultSortBy",e.target.value)}>{["date-posted","relevance","most-liked"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Max Pages"><input type="number" min="1" max="10" className={inputClass} value={String(draft.defaultMaxPages)} onChange={e=>update("defaultMaxPages",e.target.value)}/></Field><Field label="Trim Response"><Toggle checked={Boolean(draft.defaultTrim)} onChange={value=>update("defaultTrim",value)} label={draft.defaultTrim?"On":"Off"}/></Field><Field label="Transcript Enrichment"><Toggle checked={Boolean(draft.transcriptEnabled)} onChange={value=>update("transcriptEnabled",value)} label={draft.transcriptEnabled?"On":"Off"}/></Field><Field label="AI Transcript Fallback"><Toggle checked={Boolean(draft.aiTranscriptFallbackEnabled)} onChange={value=>update("aiTranscriptFallbackEnabled",value)} label={draft.aiTranscriptFallbackEnabled?"On":"Off"}/><p className="mt-2 text-[10px] text-amber-600">AI fallback dapat memakai credits lebih besar.</p></Field><Field label="Download TikTok Media"><Toggle checked={Boolean(draft.downloadMediaEnabled)} onChange={value=>update("downloadMediaEnabled",value)} label={draft.downloadMediaEnabled?"On":"Off"}/><p className="mt-2 text-[10px] text-slate-400">Tetap OFF untuk hemat biaya dan storage.</p></Field></div></section>
    <section className="panel p-6"><div className="eyebrow">Protection</div><h2 className="mt-1 font-serif text-xl">API Credit Management</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label="Daily Credit Limit"><input type="number" className={inputClass} value={String(draft.dailyCreditLimit)} onChange={e=>update("dailyCreditLimit",e.target.value)} placeholder="No limit"/></Field><Field label="Monthly Credit Limit"><input type="number" className={inputClass} value={String(draft.monthlyCreditLimit)} onChange={e=>update("monthlyCreditLimit",e.target.value)}/></Field><Field label="Warning Threshold %"><input type="number" min="1" max="99" className={inputClass} value={String(draft.warningThresholdPercent)} onChange={e=>update("warningThresholdPercent",e.target.value)}/></Field><Field label="Critical Threshold %"><input type="number" min="2" max="100" className={inputClass} value={String(draft.criticalThresholdPercent)} onChange={e=>update("criticalThresholdPercent",e.target.value)}/></Field></div><p className="mt-3 text-[10px] text-slate-500">Pada critical threshold, keyword LOW ditunda. Setelah limit tercapai hanya keyword HIGH yang tetap berjalan.</p></section>
    <ProviderHealth settings={current}/><div className="flex justify-end"><button disabled={busy} className={buttonPrimary} onClick={save}>{busy?<Loader2 className="animate-spin" size={14}/>:<Save size={14}/>}Save Settings</button></div>
  </div>;
}

function ProviderHealth({settings}:{settings:DiscoverySettings}){const rows=[["Provider",settings.provider],["Connection",settings.health.status],["Last Successful Request",formatMaybeDate(settings.health.lastSuccessfulRequestAt)],["Last Error",settings.health.lastError||"—"],["Requests Today",settings.health.requestsToday],["Credits Today",settings.health.creditsToday],["Credits This Month",settings.health.creditsThisMonth]];return <section className="panel p-6"><div className="eyebrow">Observability</div><h2 className="mt-1 font-serif text-xl">Provider Health</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{rows.map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 p-3"><div className="text-[9px] font-black uppercase text-slate-400">{label}</div><div className="mt-2 break-words text-xs font-bold">{value}</div></div>)}</div></section>;}
function UsageCard({data}:{data:Usage}){return <section className="panel p-5"><div className="eyebrow">ScrapeCreators Usage</div><h2 className="mt-1 font-serif text-xl">Credit controls</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Search Today",data.today.search_credits],["Transcript Today",data.today.transcript_credits],["Month Total",data.month.total_credits],["Remaining Budget",data.remainingBudget],["Projected Month End",data.projectedMonthEndUsage],["Credits / Relevant",data.creditsPerRelevantVideo],["Credits / Incident",data.creditsPerIncident]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 p-3"><div className="text-[9px] font-bold uppercase text-slate-400">{label}</div><div className="mt-2 font-serif text-xl">{valueOrDash(value)}</div></div>)}</div></section>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</span>{children}</label>;}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <button type="button" onClick={()=>onChange(!checked)} className={`flex h-10 w-full items-center justify-between rounded-lg border px-3 text-xs font-bold ${checked?"border-emerald-300 bg-emerald-50 text-emerald-800":"border-slate-300 bg-slate-50 text-slate-500"}`}><span>{label}</span><span className={`h-5 w-9 rounded-full p-0.5 ${checked?"bg-emerald-500":"bg-slate-300"}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${checked?"translate-x-4":""}`}/></span></button>;}
function StatusBadge({value}:{value:string}){const good=["ACTIVE","CONNECTED","SUCCESS","PROCESSED","HIGH"].includes(value);const bad=["ERROR","FAILED","DISABLED","ERROR_PERMANENT","CREDENTIAL_ERROR"].includes(value);return <span className={`inline-flex rounded-full px-2 py-1 text-[9px] font-black ${good?"bg-emerald-50 text-emerald-700":bad?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{humanize(value)}</span>;}
function Loading(){return <div className="panel flex min-h-64 items-center justify-center text-slate-400"><Loader2 className="animate-spin" size={24}/></div>;}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-xs text-slate-400">{text}</div>;}
function ErrorBox({message,retry}:{message:string;retry:()=>void}){return <div className="panel p-8 text-center"><AlertTriangle className="mx-auto text-red-500"/><p className="mt-3 text-sm text-red-700">{message}</p><button className={`${buttonSecondary} mt-4`} onClick={retry}><RefreshCw size={13}/>Retry</button></div>;}
function Toast({error,message,close}:{error:string;message:string;close:()=>void}){return <div className={`flex items-center justify-between rounded-xl border p-3 text-xs ${error?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}><span>{error||message}</span><button onClick={close}><XCircle size={15}/></button></div>;}
